language: python

os: linux
dist: xenial

jobs:
  include:
    - name: "Check Formatting"
      python: 3.6
      script: tox -e lint

python:
- 3.6
- 3.7
- 3.8
- pypy3

install:
- pip install -U tox-travis

after_success:
- coveralls

script: tox

